In [5]:
import pandas as pd
import numpy as np

In [7]:
%pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [8]:
df = pd.read_excel('Ecommerce_Unclean_Project.xlsx')

In [9]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025

In [10]:
df.tail()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
519,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,UP,Mouse,Electronics,4.0,9999.0,NaN,Card,Returned,27-02-2025
520,ORD1609,2025/03/21,Rahul,rahul99@gmail.com,9.552650e+09,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,,Wallet,Pending,28-03-2025
521,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9.700117e+09,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,,NetBanking,Delivered,16-04-2025
522,ORD1611,11-01-2025,Neha,neha22@gmail.com,9.580304e+09,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,,COD,Pending,16-01-2025
523,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9.551158e+09,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5,COD,Cancelled,09-03-2025

In [12]:
df.shape

(524, 15)

In [13]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_Name', 'Email', 'Phone', 'City',
       'State', 'Product', 'Category', 'Qty', 'Unit_Price', 'Discount',
       'Payment_Mode', 'Order_Status', 'Delivery_Date'],
      dtype='str')

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       524 non-null    str
 1   Order_Date     524 non-null    str
 2   Customer_Name  524 non-null    str
 3   Email          524 non-null    str
 4   Phone          502 non-null    float64
 5   City           524 non-null    str
 6   State          524 non-null    str
 7   Product        524 non-null    str
 8   Category       524 non-null    str
 9   Qty            457 non-null    float64
 10  Unit_Price     471 non-null    float64
 11  Discount       455 non-null    object
 12  Payment_Mode   524 non-null    str
 13  Order_Status   524 non-null    str
 14  Delivery_Date  503 non-null    str
dtypes: float64(3), object(1), str(11)
memory usage: 107.3+ KB

In [15]:
df.describe()

              Phone         Qty   Unit_Price
count  5.020000e+02  457.000000   471.000000
mean   9.544725e+09    2.800875  3168.639066
std    2.636920e+08    1.963974  2969.682209
min    9.104441e+09   -1.000000   499.000000
25%    9.315673e+09    1.000000   999.000000
50%    9.533562e+09    3.000000  1999.000000
75%    9.792574e+09    5.000000  4999.000000
max    9.999074e+09    5.000000  9999.000000

In [16]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     0
Email             0
Phone            22
City              0
State             0
Product           0
Category          0
Qty              67
Unit_Price       53
Discount         69
Payment_Mode      0
Order_Status      0
Delivery_Date    21
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(11)

In [18]:
df.drop_duplicates(inplace=True)

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.replace(
    ['N/A','NULL','',' '],np.nan,inplace=True
)

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,NaN,Wallet,Cancelled,07-04-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,UP,Mouse,Electronics,4.0,9999.0,NaN,Card,Returned,27-02-2025
520,ORD1609,2025/03/21,Rahul,rahul99@gmail.com,9.552650e+09,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,NaN,Wallet,Pending,28-03-2025
521,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9.700117e+09,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,NaN,NetBanking,Delivered,16-04-2025
522,ORD1611,11-01-2025,Neha,neha22@gmail.com,9.580304e+09,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,NaN,COD,Pending,16-01-2025
523,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9.551158e+09,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5,COD,Cancelled,09-03-2025

In [21]:
df.isnull().sum()

Order_ID           6
Order_Date         0
Customer_Name      0
Email              0
Phone             22
City               0
State              0
Product            0
Category           0
Qty               65
Unit_Price        51
Discount         148
Payment_Mode       0
Order_Status       0
Delivery_Date     21
dtype: int64

In [23]:
df = df.apply(lambda x: x.map(lambda y: y.strip() if isinstance(y, str) else y))

In [25]:
for col in df.select_dtypes(include="str").columns:
    df[col] = df[col].map(lambda x: x.strip() if isinstance(x, str) else x)

df["Customer_Name"] = df["Customer_Name"].str.title()
df["City"] = df["City"].str.title()
df["State"] = df["State"].str.title()
df["Product"] = df["Product"].str.title()
df["Category"] = df["Category"].str.title()

df["Email"] = df["Email"].str.lower()

df["Payment_Mode"] = df["Payment_Mode"].str.title()
df["Order_Status"] = df["Order_Status"].str.title()

df["Order_Date"] = pd.to_datetime(
    df["Order_Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

df["Delivery_Date"] = pd.to_datetime(
    df["Delivery_Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

df["Qty"] = pd.to_numeric(df["Qty"], errors="coerce")
df["Unit_Price"] = pd.to_numeric(df["Unit_Price"], errors="coerce")
df["Discount"] = pd.to_numeric(df["Discount"], errors="coerce")

In [26]:
 #numeric coloumn list
df.describe()

,Order_Date,Phone,Qty,Unit_Price,Discount,Delivery_Date
count,446,4.910000e+02,448.000000,462.000000,365.000000,181
mean,2025-04-01 20:39:49.237668,9.543738e+09,2.794643,3176.272727,10.917808,2025-06-18 15:22:52.375690
min,2025-01-01 00:00:00,9.104441e+09,-1.000000,499.000000,0.000000,2025-01-02 00:00:00
25%,2025-02-14 00:00:00,9.313005e+09,1.000000,999.000000,5.000000,2025-04-03 00:00:00
50%,2025-04-03 12:00:00,9.532206e+09,3.000000,1999.000000,10.000000,2025-07-03 00:00:00
75%,2025-05-15 18:00:00,9.793310e+09,5.000000,4999.000000,15.000000,2025-09-04 00:00:00
max,2025-06-30 00:00:00,9.999074e+09,5.000000,9999.000000,20.000000,2025-12-06 00:00:00
std,NaN,2.647419e+08,1.976997,2971.838671,7.113201,NaN

In [27]:
df.isnull().sum()

Order_ID           6
Order_Date        67
Customer_Name      0
Email              0
Phone             22
City               0
State              0
Product            0
Category           0
Qty               65
Unit_Price        51
Discount         148
Payment_Mode       0
Order_Status       0
Delivery_Date    332
dtype: int64

In [28]:
df = df.dropna(subset=["Order_ID"])

In [29]:
df[df["Order_Date"].isnull()]

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
7,ORD1009,NaT,Rahul,rahul99@gmail.com,9.552650e+09,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,NaN,Wallet,Pending,NaT
16,ORD1018,NaT,Amit,amit96@gmail.com,9.124087e+09,Mumbai,Maharashtra,Shoes,Fashion,2.0,4999.0,5.0,Wallet,Delivered,NaT
25,ORD1027,NaT,Rahul,rahul7@gmail.com,9.924849e+09,Pune,Maharashtra,Chair,Furniture,NaN,NaN,15.0,Upi,Returned,NaT
34,ORD1036,NaT,Rohit,rohit22@gmail.com,9.900320e+09,Pune,Maharashtra,Watch,Fashion,-1.0,4999.0,5.0,Netbanking,Cancelled,2025-05-03
38,ORD1040,NaT,Sneha,sneha23@gmail.com,9.116125e+09,Delhi,Delhi,Bottle,Home,5.0,1499.0,10.0,Card,Returned,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,ORD1477,NaT,Vikas,vikas1@gmail.com,9.904339e+09,Bengaluru,Karnataka,Chair,Furniture,2.0,499.0,0.0,Cod,Delivered,NaT
478,ORD1480,NaT,Rohit,rohit15@gmail.com,9.309551e+09,Pune,Maharashtra,Chair,Furniture,4.0,4999.0,15.0,Netbanking,Delivered,NaT
484,ORD1486,NaT,Vikas,vikas78@gmail.com,9.812672e+09,Bengaluru,Karnataka,Laptop,Electronics,3.0,4999.0,0.0,Wallet,Delivered,2025-02-06
493,ORD1495,NaT,Sneha,sneha59@gmail.com,9.580925e+09,Bengaluru,Karnataka,Mouse,Electronics,1.0,499.0,NaN,Netbanking,Returned,NaT
520,ORD1609,NaT,Rahul,rahul99@gmail.com,9.552650e+09,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,NaN,Wallet,Pending,NaT

In [30]:
pd.crosstab(
    df["Order_Status"],
    df["Delivery_Date"].isna()
)

Delivery_Date  False  True
Order_Status
Cancelled         48     76
Delivered         45     89
Pending           48     73
Returned          40     88

In [31]:
# Delivered orders should have a delivery date
df[(df["Order_Status"] == "Delivered") & (df["Delivery_Date"].isna())]

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
8,ORD1010,2025-04-10,Rohit,rohit96@gmail.com,9.700117e+09,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,NaN,Netbanking,Delivered,NaT
16,ORD1018,NaT,Amit,amit96@gmail.com,9.124087e+09,Mumbai,Maharashtra,Shoes,Fashion,2.0,4999.0,5.0,Wallet,Delivered,NaT
27,ORD1029,2025-02-06,Rahul,rahul82@gmail.com,9.689560e+09,Pune,Maharashtra,Bottle,Home,5.0,1499.0,NaN,Cod,Delivered,NaT
29,ORD1031,2025-03-20,Sneha,sneha76gmail.com,9.946816e+09,Mumbai,Maharashtra,Shoes,Fashion,5.0,499.0,20.0,Card,Delivered,NaT
30,ORD1032,2025-04-12,Neha,neha79@gmail.com,9.312273e+09,Pune,Maharashtra,Bottle,Home,1.0,499.0,20.0,Upi,Delivered,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488,ORD1490,2025-05-08,Sneha,sneha22@gmail.com,9.311385e+09,Pune,Maharashtra,Laptop,Electronics,2.0,9999.0,20.0,Card,Delivered,NaT
492,ORD1494,2025-03-20,Sneha,sneha50@gmail.com,9.703494e+09,Delhi,Delhi,Bottle,Home,5.0,999.0,0.0,Wallet,Delivered,NaT
498,ORD1500,2025-05-15,Priya,priya67@gmail.com,9.848201e+09,Pune,Maharashtra,Laptop,Electronics,3.0,NaN,15.0,Upi,Delivered,NaT
511,ORD1600,2025-05-15,Priya,priya67@gmail.com,9.848201e+09,Pune,Maharashtra,Laptop,Electronics,3.0,NaN,15.0,Upi,Delivered,NaT
521,ORD1610,2025-04-10,Rohit,rohit96@gmail.com,9.700117e+09,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,NaN,Netbanking,Delivered,NaT

In [32]:
df[(df["Order_Status"] != "Delivered") & (df["Delivery_Date"].notna())]

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,Upi,Pending,2025-03-07
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2025-09-02
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,Cod,Returned,2025-08-05
4,ORD1006,2025-04-02,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,NaN,Wallet,Cancelled,2025-07-04
10,ORD1012,2025-03-03,Vikas,vikas46@gmail.com,9.551158e+09,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5.0,Cod,Cancelled,2025-09-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
513,ORD1602,2025-06-30,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,Upi,Pending,2025-03-07
514,ORD1603,2025-02-03,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2025-09-02
515,ORD1604,2025-05-06,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,Cod,Returned,2025-08-05
517,ORD1606,2025-04-02,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,NaN,Wallet,Cancelled,2025-07-04
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9.551158e+09,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5.0,Cod,Cancelled,2025-09-03

In [33]:
df_clean = df.copy()

In [34]:
df_clean.duplicated().sum()

np.int64(0)

In [35]:
for col in df_clean.select_dtypes(include="str").columns:
    df_clean[col] = df_clean[col].map(
        lambda x: x.strip() if isinstance(x, str) else x
    )

In [36]:
df_clean["Customer_Name"] = df_clean["Customer_Name"].str.title()
df_clean["City"] = df_clean["City"].str.title()
df_clean["State"] = df_clean["State"].str.title()
df_clean["Product"] = df_clean["Product"].str.title()
df_clean["Category"] = df_clean["Category"].str.title()

df_clean["Email"] = df_clean["Email"].str.lower()

df_clean["Payment_Mode"] = df_clean["Payment_Mode"].str.title()
df_clean["Order_Status"] = df_clean["Order_Status"].str.title()

In [37]:
df_clean["Order_Date"] = pd.to_datetime(
    df_clean["Order_Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

df_clean["Delivery_Date"] = pd.to_datetime(
    df_clean["Delivery_Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

In [38]:
df_clean["Qty"] = pd.to_numeric(
    df_clean["Qty"], errors="coerce"
)

df_clean["Unit_Price"] = pd.to_numeric(
    df_clean["Unit_Price"], errors="coerce"
)

df_clean["Discount"] = pd.to_numeric(
    df_clean["Discount"], errors="coerce"
)

In [39]:
df_clean["Phone"] = df_clean["Phone"].astype("string")

In [40]:
df_clean.isnull().sum()

Order_ID           0
Order_Date        67
Customer_Name      0
Email              0
Phone             22
City               0
State              0
Product            0
Category           0
Qty               65
Unit_Price        51
Discount         146
Payment_Mode       0
Order_Status       0
Delivery_Date    326
dtype: int64

In [41]:
df_clean = df_clean.dropna(subset=["Order_ID"])

In [42]:
df_clean = df_clean.dropna(subset=["Order_Date"])

In [46]:
df_clean["Phone"] = df_clean["Phone"].fillna("Unknown")

In [47]:
df_clean.loc[df_clean["Qty"] <= 0, "Qty"] = np.nan

In [48]:
df_clean["Qty"] = df_clean["Qty"].fillna(
    df_clean["Qty"].median()
)

In [49]:
df_clean["Unit_Price"] = df_clean["Unit_Price"].fillna(
    df_clean["Unit_Price"].median()
)

In [50]:
df_clean["Discount"] = df_clean["Discount"].fillna(0)

In [51]:
invalid_dates = df_clean[
    df_clean["Delivery_Date"].notna() &
    (df_clean["Delivery_Date"] < df_clean["Order_Date"])
]

In [52]:
df_clean.loc[
    df_clean["Delivery_Date"] < df_clean["Order_Date"],
    "Delivery_Date"
] = pd.NaT

In [53]:
df_clean[
    (df_clean["Order_Status"] == "Delivered") &
    (df_clean["Delivery_Date"].isna())
]

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
8,ORD1010,2025-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,1999.0,0.0,Netbanking,Delivered,NaT
27,ORD1029,2025-02-06,Rahul,rahul82@gmail.com,9689560222.0,Pune,Maharashtra,Bottle,Home,5.0,1499.0,0.0,Cod,Delivered,NaT
28,ORD1030,2025-04-25,Rahul,rahul52@gmail.com,9882683944.0,Mumbai,Maharashtra,Shoes,Fashion,1.0,9999.0,20.0,Upi,Delivered,NaT
29,ORD1031,2025-03-20,Sneha,sneha76gmail.com,9946815525.0,Mumbai,Maharashtra,Shoes,Fashion,5.0,499.0,20.0,Card,Delivered,NaT
30,ORD1032,2025-04-12,Neha,neha79@gmail.com,9312273373.0,Pune,Maharashtra,Bottle,Home,1.0,499.0,20.0,Upi,Delivered,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,ORD1500,2025-05-15,Priya,priya67@gmail.com,9848200695.0,Pune,Maharashtra,Laptop,Electronics,3.0,1999.0,15.0,Upi,Delivered,NaT
499,ORD1501,2025-04-28,Amit,amit26@gmail.com,9873317457.0,Lucknow,Up,Chair,Furniture,3.0,1499.0,15.0,Wallet,Delivered,NaT
511,ORD1600,2025-05-15,Priya,priya67@gmail.com,9848200695.0,Pune,Maharashtra,Laptop,Electronics,3.0,1999.0,15.0,Upi,Delivered,NaT
512,ORD1601,2025-04-28,Amit,amit26@gmail.com,9873317457.0,Lucknow,Up,Chair,Furniture,3.0,1499.0,15.0,Wallet,Delivered,NaT
521,ORD1610,2025-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,1999.0,0.0,Netbanking,Delivered,NaT

In [54]:
df_clean.loc[
    df_clean["Order_Status"] != "Delivered",
    "Delivery_Date"
] = pd.NaT

In [55]:
email_pattern = r"^[\w\.-]+@[\w\.-]+\.\w+$"

df_clean["Valid_Email"] = df_clean["Email"].str.match(
    email_pattern,
    na=False
)

In [56]:
df_clean[~df_clean["Valid_Email"]]

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Valid_Email
29,ORD1031,2025-03-20,Sneha,sneha76gmail.com,9946815525.0,Mumbai,Maharashtra,Shoes,Fashion,5.0,499.0,20.0,Card,Delivered,NaT,False
60,ORD1062,2025-06-29,Amit,amit18gmail.com,9177835684.0,Pune,Maharashtra,Watch,Fashion,1.0,499.0,20.0,Upi,Delivered,2025-07-07,False
91,ORD1093,2025-06-21,Priya,priya20gmail.com,9980807282.0,Mumbai,Maharashtra,Laptop,Electronics,2.0,9999.0,0.0,Netbanking,Returned,NaT,False
122,ORD1124,2025-03-20,Rahul,rahul45gmail.com,9927031899.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,20.0,Card,Pending,NaT,False
153,ORD1155,2025-04-07,Amit,amit98gmail.com,9597661845.0,Mumbai,Maharashtra,Watch,Fashion,1.0,1499.0,0.0,Cod,Delivered,NaT,False
184,ORD1186,2025-03-31,Vikas,vikas44gmail.com,9462113296.0,Mumbai,Maharashtra,Chair,Furniture,3.0,499.0,10.0,Card,Pending,NaT,False
215,ORD1217,2025-04-25,Neha,neha6gmail.com,9913448662.0,Bengaluru,Karnataka,Laptop,Electronics,5.0,9999.0,10.0,Card,Returned,NaT,False
246,ORD1248,2025-06-13,Priya,priya58gmail.com,9202774742.0,Bengaluru,Karnataka,Mouse,Electronics,3.0,4999.0,20.0,Card,Pending,NaT,False
308,ORD1310,2025-03-10,Amit,amit7gmail.com,9303283049.0,Lucknow,Up,Bottle,Home,5.0,2599.0,10.0,Card,Cancelled,NaT,False
339,ORD1341,2025-05-05,Rahul,rahul93gmail.com,9182121049.0,Jaipur,Rajasthan,Laptop,Electronics,1.0,4999.0,15.0,Card,Pending,NaT,False
370,ORD1372,2025-02-04,Rahul,rahul15gmail.com,9509340822.0,Delhi,Delhi,Shoes,Fashion,1.0,499.0,0.0,Netbanking,Returned,NaT,False
401,ORD1403,2025-04-15,Rohit,rohit30gmail.com,9450277671.0,Jaipur,Rajasthan,Chair,Furniture,4.0,1499.0,15.0,Cod,Cancelled,NaT,False
432,ORD1434,2025-01-12,Vikas,vikas94gmail.com,9723823343.0,Jaipur,Rajasthan,Chair,Furniture,5.0,1999.0,0.0,Wallet,Cancelled,NaT,False
463,ORD1465,2025-04-13,Priya,priya27gmail.com,9263255819.0,Bengaluru,Karnataka,Mouse,Electronics,5.0,2599.0,0.0,Card,Returned,NaT,False
494,ORD1496,2025-03-17,Amit,amit43gmail.com,9916348209.0,Delhi,Delhi,Bottle,Home,3.0,999.0,0.0,Cod,Returned,NaT,False

In [57]:
df_clean = df_clean.drop(columns=["Valid_Email"])

In [58]:
df_clean.isnull().sum()

Order_ID           0
Order_Date         0
Customer_Name      0
Email              0
Phone              0
City               0
State              0
Product            0
Category           0
Qty                0
Unit_Price         0
Discount           0
Payment_Mode       0
Order_Status       0
Delivery_Date    415
dtype: int64

In [59]:
df_clean.dtypes

Order_ID                    str
Order_Date       datetime64[us]
Customer_Name               str
Email                       str
Phone                    string
City                        str
State                       str
Product                     str
Category                    str
Qty                     float64
Unit_Price              float64
Discount                float64
Payment_Mode                str
Order_Status                str
Delivery_Date    datetime64[us]
dtype: object

In [60]:
df_clean.describe()

,Order_Date,Qty,Unit_Price,Discount,Delivery_Date
count,440,440.000000,440.000000,440.000000,25
mean,2025-04-02 03:16:21.818181,3.288636,3106.500000,7.840909,2025-07-31 05:45:36
min,2025-01-01 00:00:00,1.000000,499.000000,0.000000,2025-02-02 00:00:00
25%,2025-02-15 00:00:00,3.000000,1499.000000,0.000000,2025-06-04 00:00:00
50%,2025-04-04 00:00:00,3.000000,1999.000000,5.000000,2025-08-03 00:00:00
75%,2025-05-15 06:00:00,5.000000,4999.000000,15.000000,2025-10-05 00:00:00
max,2025-06-30 00:00:00,5.000000,9999.000000,20.000000,2025-12-05 00:00:00
std,NaN,1.286289,2913.891499,7.805854,NaN

In [61]:
df_clean[df_clean["Delivery_Date"].isna()]["Order_Status"].value_counts()

Order_Status
Cancelled    113
Returned     110
Pending      101
Delivered     91
Name: count, dtype: int64

In [62]:
pd.crosstab(
    df_clean["Order_Status"],
    df_clean["Delivery_Date"].isna()
)

Delivery_Date  False  True
Order_Status
Cancelled          0    113
Delivered         25     91
Pending            0    101
Returned           0    110

In [63]:
invalid_dates = df_clean[
    df_clean["Delivery_Date"].notna() &
    (df_clean["Delivery_Date"] < df_clean["Order_Date"])
]

print(invalid_dates.shape)

(0, 15)

In [64]:
print("Duplicates:", df_clean.duplicated().sum())

print("\nMissing Values:")
print(df_clean.isnull().sum())

print("\nData Types:")
print(df_clean.dtypes)

print("\nShape:")
print(df_clean.shape)

Duplicates: 0

Missing Values:
Order_ID           0
Order_Date         0
Customer_Name      0
Email              0
Phone              0
City               0
State              0
Product            0
Category           0
Qty                0
Unit_Price         0
Discount           0
Payment_Mode       0
Order_Status       0
Delivery_Date    415
dtype: int64

Data Types:
Order_ID                    str
Order_Date       datetime64[us]
Customer_Name               str
Email                       str
Phone                    string
City                        str
State                       str
Product                     str
Category                    str
Qty                     float64
Unit_Price              float64
Discount                float64
Payment_Mode                str
Order_Status                str
Delivery_Date    datetime64[us]
dtype: object

Shape:
(440, 15)

In [65]:
df_clean.describe()

,Order_Date,Qty,Unit_Price,Discount,Delivery_Date
count,440,440.000000,440.000000,440.000000,25
mean,2025-04-02 03:16:21.818181,3.288636,3106.500000,7.840909,2025-07-31 05:45:36
min,2025-01-01 00:00:00,1.000000,499.000000,0.000000,2025-02-02 00:00:00
25%,2025-02-15 00:00:00,3.000000,1499.000000,0.000000,2025-06-04 00:00:00
50%,2025-04-04 00:00:00,3.000000,1999.000000,5.000000,2025-08-03 00:00:00
75%,2025-05-15 06:00:00,5.000000,4999.000000,15.000000,2025-10-05 00:00:00
max,2025-06-30 00:00:00,5.000000,9999.000000,20.000000,2025-12-05 00:00:00
std,NaN,1.286289,2913.891499,7.805854,NaN

In [66]:
# Feature Engineering

# 1. Total Order Amount
df_clean["Total_Amount"] = (
    df_clean["Qty"] * df_clean["Unit_Price"]
)

# 2. Discount Amount
df_clean["Discount_Amount"] = (
    df_clean["Total_Amount"] * df_clean["Discount"] / 100
)

# 3. Final Amount after Discount
df_clean["Final_Amount"] = (
    df_clean["Total_Amount"] - df_clean["Discount_Amount"]
)

# 4. Order Year
df_clean["Order_Year"] = df_clean["Order_Date"].dt.year

# 5. Order Month
df_clean["Order_Month"] = df_clean["Order_Date"].dt.month

# 6. Order Month Name
df_clean["Order_Month_Name"] = (
    df_clean["Order_Date"].dt.month_name()
)

# 7. Order Day
df_clean["Order_Day"] = df_clean["Order_Date"].dt.day

# 8. Order Day Name
df_clean["Order_Day_Name"] = (
    df_clean["Order_Date"].dt.day_name()
)

# 9. Weekend Indicator
df_clean["Is_Weekend"] = (
    df_clean["Order_Date"].dt.dayofweek >= 5
)

# 10. Delivery Days
df_clean["Delivery_Days"] = (
    df_clean["Delivery_Date"] - df_clean["Order_Date"]
).dt.days

# 11. High Value Order
df_clean["High_Value_Order"] = (
    df_clean["Final_Amount"] >= 5000
)

# 12. Quantity Category
df_clean["Quantity_Category"] = pd.cut(
    df_clean["Qty"],
    bins=[0, 2, 4, 5],
    labels=["Low", "Medium", "High"]
)

# Check new features
df_clean.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Final_Amount,Order_Year,Order_Month,Order_Month_Name,Order_Day,Order_Day_Name,Is_Weekend,Delivery_Days,High_Value_Order,Quantity_Category
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,...,7996.00,2025,6,June,30,Monday,False,NaN,True,Medium
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,...,19996.00,2025,2,February,3,Monday,False,NaN,True,High
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,...,5697.15,2025,5,May,6,Tuesday,False,NaN,True,Medium
3,ORD1005,2025-01-20,Vikas,vikas51@gmail.com,9495120474.0,Bengaluru,Karnataka,Laptop,Electronics,3.0,...,5097.45,2025,1,January,20,Monday,False,NaN,True,Medium
4,ORD1006,2025-04-02,Rohit,rohit71@gmail.com,9237331620.0,Pune,Maharashtra,Bottle,Home,3.0,...,5997.00,2025,4,April,2,Wednesday,False,NaN,True,Medium

In [67]:
df_clean[
    [
        "Qty",
        "Unit_Price",
        "Discount",
        "Total_Amount",
        "Discount_Amount",
        "Final_Amount",
        "Order_Month",
        "Order_Month_Name",
        "Order_Day_Name",
        "Is_Weekend",
        "Delivery_Days",
        "High_Value_Order",
        "Quantity_Category"
    ]
].head(10)

,Qty,Unit_Price,Discount,Total_Amount,Discount_Amount,Final_Amount,Order_Month,Order_Month_Name,Order_Day_Name,Is_Weekend,Delivery_Days,High_Value_Order,Quantity_Category
0,4.0,1999.0,0.0,7996.0,0.00,7996.00,6,June,Monday,False,NaN,True,Medium
1,5.0,4999.0,20.0,24995.0,4999.00,19996.00,2,February,Monday,False,NaN,True,High
2,3.0,1999.0,5.0,5997.0,299.85,5697.15,5,May,Tuesday,False,NaN,True,Medium
3,3.0,1999.0,15.0,5997.0,899.55,5097.45,1,January,Monday,False,NaN,True,Medium
4,3.0,1999.0,0.0,5997.0,0.00,5997.00,4,April,Wednesday,False,NaN,True,Medium
5,3.0,499.0,20.0,1497.0,299.40,1197.60,2,February,Monday,False,NaN,False,Medium
6,4.0,9999.0,0.0,39996.0,0.00,39996.00,2,February,Monday,False,NaN,True,Medium
8,1.0,1999.0,0.0,1999.0,0.00,1999.00,4,April,Thursday,False,NaN,False,Low
9,3.0,999.0,0.0,2997.0,0.00,2997.00,1,January,Saturday,True,NaN,False,Medium
10,3.0,999.0,5.0,2997.0,149.85,2847.15,3,March,Monday,False,NaN,False,Medium

In [68]:
df_clean.columns

Index(['Order_ID', 'Order_Date', 'Customer_Name', 'Email', 'Phone', 'City',
       'State', 'Product', 'Category', 'Qty', 'Unit_Price', 'Discount',
       'Payment_Mode', 'Order_Status', 'Delivery_Date', 'Total_Amount',
       'Discount_Amount', 'Final_Amount', 'Order_Year', 'Order_Month',
       'Order_Month_Name', 'Order_Day', 'Order_Day_Name', 'Is_Weekend',
       'Delivery_Days', 'High_Value_Order', 'Quantity_Category'],
      dtype='str')

In [69]:
df_clean.to_csv("Ecommerce_Cleaned_Featured.csv", index=False)

In [70]:
print("Rows:", df_clean.shape[0])
print("Columns:", df_clean.shape[1])

Rows: 440
Columns: 27

In [71]:
df_clean["Order_Status"].value_counts()

Order_Status
Delivered    116
Cancelled    113
Returned     110
Pending      101
Name: count, dtype: int64

In [72]:
df_clean.groupby("Category")["Final_Amount"].sum().sort_values(
    ascending=False
)

Category
Electronics    1611759.65
Fashion        1162607.35
Home            732292.45
Furniture       720652.00
Name: Final_Amount, dtype: float64

In [73]:
df_clean.groupby("Product")["Final_Amount"].sum().sort_values(
    ascending=False
)

Product
Laptop    848504.40
Mouse     763255.25
Bottle    732292.45
Chair     720652.00
Watch     603410.90
Shoes     559196.45
Name: Final_Amount, dtype: float64

In [74]:
df_clean.groupby("City")["Final_Amount"].sum().sort_values(
    ascending=False
)

City
Bengaluru    912456.05
Pune         910278.90
Lucknow      689481.00
Delhi        612384.95
Mumbai       566703.05
Jaipur       536007.50
Name: Final_Amount, dtype: float64

In [75]:
monthly_sales = (
    df_clean.groupby("Order_Month_Name")["Final_Amount"]
    .sum()
)

In [76]:
total_orders = df_clean["Order_ID"].nunique()

In [77]:
total_revenue = df_clean["Final_Amount"].sum()

In [78]:
average_order_value = df_clean["Final_Amount"].mean()

In [79]:
total_quantity = df_clean["Qty"].sum()

In [80]:
average_discount = df_clean["Discount"].mean()

In [81]:
delivered_orders = (
    df_clean["Order_Status"] == "Delivered"
).sum()

In [82]:
return_rate = (
    (df_clean["Order_Status"] == "Returned").sum()
    / len(df_clean)
) * 100

In [83]:
cancellation_rate = (
    (df_clean["Order_Status"] == "Cancelled").sum()
    / len(df_clean)
) * 100

In [84]:
df_clean.to_excel(
    "Ecommerce_Final.xlsx",
    index=False
)

print("Final file exported successfully!")

Final file exported successfully!

In [85]:
import os

print(os.path.abspath("Ecommerce_Final.xlsx"))

C:\Users\aravc\OneDrive\Desktop\End to End Project\Ecommerce_Final.xlsx